name: Continous Deployment

on:
  workflow_run:
    workflows: ["Backend CI - Build & Scan", "CI Frontend - Build & Scan"]
    types: [completed]
    branches: [main]

jobs:
  deploy-to-local:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Load Images to Kind
        run: |
          # Build images locally on the runner
          docker build -t backend:latest ./backend
          docker build -t frontend:latest ./frontend
          
          # Load them into the kind cluster
          kind load docker-image backend:latest --name secure-platform-cluster
          kind load docker-image frontend:latest --name secure-platform-cluster

      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s/manifests/network-policy.yaml
          kubectl apply -f k8s/manifests/backend.yaml
          kubectl apply -f k8s/manifests/frontend.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/backend-deployment -n secure-app
          kubectl rollout status deployment/frontend-deployment -n secure-app
